<!DOCTYPE html>
<html lang="en-US">
<head>
    <?= $this->meta->head($index); ?>
</head>
<body>
    <h1>Post Search</h1>
    
    <ul id="result">
    </ul>
    
    <ul id="pager">
    </ul>
    
    <?= $this->meta->foot($index); ?>
    
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="<?= $this->asset('js/post-search.js') ?>"></script>
    <script>
        PS.init({
            key: '<?= $this->setting->post_search_gce_key ?>',
            cx : '<?= $this->setting->post_search_gce_cx ?>'
        });
        
        var qs = location.search.match(/q=([^&]+)/);
        if(qs && qs[1]){
            var q = qs[1];
            
            var page = location.search.match(/page=([0-9]+)/);
            if(!page || !page[1])
                page = 1;
            else
                page = page[1];
            
            PS.find(q, page, function(err, res){
                if(err)
                    return console.log(err);
                
                for(var i=0; i<res.items.length; i++){
                    var post = res.items[i];
                    var li = $('<li></li>');
                    var a = $('<a href="'+post.link+'">'+post.title+'</a>');
                    li.append(a);
                    $('#result').append(li);
                }
                
                for(var i=0; i<res.pages; i++){
                    var page = i+1;
                    var li = $('<li>');
                    var a  = $('<a href="?q='+q+'&page='+page+'">'+page+'</a>');
                    li.append(a);
                    $('#pager').append(li);
                }
            });
        }
        
    </script>
</body>
</html>